# Generated by Django 5.0.6 on 2024-06-14 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_formapagamento_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.produto'),
        ),
    ]
