# Generated by Django 5.0.6 on 2024-06-14 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='produto',
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.produto'),
        ),
    ]
