# Generated by Django 5.0.6 on 2024-06-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='nome_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='valor',
            new_name='valor_produto',
        ),
    ]
