# Generated by Django 5.0.6 on 2024-05-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dt_entrada', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('codigo_de_barra', models.IntegerField()),
                ('validade', models.DateField()),
            ],
        ),
    ]
