# Generated by Django 5.0.6 on 2024-06-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('dt_estoque', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedor', models.ManyToManyField(to='core.fornecedor')),
            ],
        ),
    ]
