# Generated by Django 5.0.7 on 2024-08-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
